language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAJTVCVXVCSAOP6OFA
  secret_access_key:
    secure: 3krsUOJaVGJTdUu+D0U1OS/qtjjNtqvfTMKlF9G38Cs+XOOXoyHsXJbQ/h86xb29xpT/kbr8G55GYgAHl94i1La/kiCvdxX06T+FZ4q+iXfyb/rvryWGREKTfGginRkHIgysv0RdRULzYJUtgNUU1RUz8Bka/+ekdoKfZyyCFFP+6/jJXskZ8Q7j0CIbkL1+Q1jDO7yhR7KrdF5ggb5Chgkzu7L4iO8YoA3lqzZh05feRn9uG0+mHgFy2oyauCRc3FWuPPGl/VB69DB5YQa63Utg+/de3sdan/Rrcp1ev+0c2RfhwiD9xOpB2XWB7/tFnmKyKPtWUnsiP4LxywAxd4O9/TvcEwRH3OaDnmVymtm2kJpbdQ5HGl4kjoM2k0z6jULoyOlunE+F6sV8JNwvxgZYGcKjrfHxBDTsi17JENesBBLjdVlyqbl21DRU096ur4BBPLgdYa9DfqY7IHBenGeeB4RLpBX4Mkhuf59wiIDJtDWtUJJHcaTJuJU5To8Kv2lK/vN5Q+S5ZMNA2+GNksFoZE8qTpBl1HhMrFNezCDTs8HFW2TOucfcpp3CIS26KfNqDWwRa/mq/oQZYhgBPV9V/cewuw/PQKV50vz4n6GLobQpA4S4PuJx1ooBHkseJu+xz8x6kECkf8wDWY0ejS7lG8vUJCihEOCiB+zd6TI=
  bucket: esoma-tril
  local-dir: build/
  acl: public_read
  on:
    repo: Kairn/tri-land
  skip_cleanup: 'true'